<a href="https://colab.research.google.com/github/AashiGarg-tech/Code-mix-Sentiment-Analysis-of-Hinglish-Tweets/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df1 = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_14k.csv")
df2 = pd.read_csv("/Users/aashigarg/Downloads/Data.csv")

print("cleaned_dataset_14k:", df1.shape)
print("Data.csv:", df2.shape)

cleaned_dataset_14k: (13966, 4)
Data.csv: (17000, 3)

In [ ]:
print(df1.columns)
print(df2.columns)

Index(['id', 'sentence', 'label', 'sentiment'], dtype='object')
Index(['ID', 'Tweet', 'Sentiment Polarity'], dtype='object')

In [ ]:
import pandas as pd

# Load both datasets
df1 = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_14k.csv")
df2 = pd.read_csv("/Users/aashigarg/Downloads/Data.csv")

# Step 1: Rename columns in Data.csv to match df1
df2 = df2.rename(columns={
    "ID": "id",
    "Tweet": "sentence",
    "Sentiment Polarity": "label"
})

# Step 2: (Optional) if 'label' values are textual (like "Positive", "Negative"), convert them to numeric
# Only do this if df1['label'] is numeric
if df1['label'].dtype != df2['label'].dtype:
    mapping = {"Positive": 2, "Neutral": 1, "Negative": 0}
    df2['label'] = df2['label'].map(mapping)

# Step 3: Take 16k entries from Data.csv
df2_sample = df2.sample(n=16000, random_state=42)
print("Data.csv sample shape:", df2_sample.shape)

# Step 4: Combine both datasets
combined = pd.concat([df1, df2_sample], axis=0).reset_index(drop=True)
print("Before dropping duplicates:", combined.shape)

# Step 5: Remove duplicates based on text
combined = combined.drop_duplicates(subset=["sentence"]).reset_index(drop=True)
print("After dropping duplicates:", combined.shape)

# Step 6: Shuffle the final dataset
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

# Step 7: Save final 30k dataset
combined.to_csv("final_dataset_30k.csv", index=False)
print("✅ Final dataset saved as final_dataset_30k.csv")

Data.csv sample shape: (16000, 3)
Before dropping duplicates: (29966, 4)
After dropping duplicates: (29098, 4)
✅ Final dataset saved as final_dataset_30k.csv

In [ ]:
print(combined['label'].value_counts())
print(combined['sentence'].str.split().str.len().describe())

label
1.0    5132
2.0    4485
0.0    4025
Name: count, dtype: int64
count    29097.000000
mean        13.869815
std          6.507031
min          1.000000
25%          9.000000
50%         13.000000
75%         18.000000
max         92.000000
Name: sentence, dtype: float64

In [ ]:
import pandas as pd

df = pd.read_csv("final_dataset_30k.csv")

# Check missing values in label column
print("Missing labels:", df['label'].isna().sum())

# Check label types and unique values
print("Unique label values:", df['label'].unique())

Missing labels: 15456
Unique label values: [nan  1.  0.  2.]

In [ ]:
import pandas as pd

df = pd.read_csv("final_dataset_30k.csv")
print(df.shape)
print(df.columns)

(29098, 4)
Index(['id', 'sentence', 'label', 'sentiment'], dtype='object')

In [ ]:
print(df[df['label'].isna()].head())

      id                                           sentence  label sentiment
0   6936  tujh bahut logo shraap diya teri lutiya doobeg...    NaN       NaN
1  17312                          phir mehboob na kaha pora    NaN       NaN
3  14211                   thank much least time knew build    NaN       NaN
4  40779  itn saal bad kya apn firbhi sawal banta defin ...    NaN       NaN
7  20652  yogendrayadav modi sarkar pichd vargn pm banay...    NaN       NaN

In [ ]:
df1 = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_14k.csv")
df2_sample = df2_sample[['id', 'sentence', 'label']]  # keep consistent columns

combined = pd.concat([df1, df2_sample], axis=0).reset_index(drop=True)
print("Before dropping duplicates:", combined.shape)

combined = combined.drop_duplicates(subset=["sentence"]).reset_index(drop=True)
print("After dropping duplicates:", combined.shape)

combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)
combined.to_csv("final_dataset_30k_fixed.csv", index=False)
print("✅ Final dataset saved as final_dataset_30k_fixed.csv")

Before dropping duplicates: (29966, 4)
After dropping duplicates: (29098, 4)
✅ Final dataset saved as final_dataset_30k_fixed.csv

In [ ]:
df = pd.read_csv("final_dataset_30k_fixed.csv")
print(df['label'].value_counts())
print(df['label'].isna().sum())

label
1.0    5132
2.0    4485
0.0    4025
Name: count, dtype: int64
15456

In [ ]:
import pandas as pd

# 1. Load both original files
df1 = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_14k.csv")
df2 = pd.read_csv("/Users/aashigarg/Downloads/Data.csv")

print("cleaned_dataset_14k:", df1.shape)
print("Data.csv:", df2.shape)

# 2. Confirm the columns in each file
print("df1 columns:", df1.columns)
print("df2 columns:", df2.columns)

# 3. Clean and prepare Data.csv
#    (this is the key part—make sure we actually see values before mapping)
print("\nUnique Sentiment values before mapping:", df2['Sentiment Polarity'].unique())

mapping = {"Positive": 2.0, "Neutral": 1.0, "Negative": 0.0}
df2['label'] = df2['Sentiment Polarity'].map(mapping)

# 4. Check that mapping worked
print("Unique labels after mapping:", df2['label'].unique())

# 5. Keep only the needed columns and rename them
df2 = df2[['ID', 'Tweet', 'label']].rename(columns={'ID': 'id', 'Tweet': 'sentence'})

# 6. Take a random sample of 16 000 rows
df2_sample = df2.sample(n=16000, random_state=42)
print("Data.csv sample shape:", df2_sample.shape)
print("Sample label counts:\n", df2_sample['label'].value_counts())

# 7. Align df1 to the same 3 columns
df1 = df1[['id', 'sentence', 'label']]

# 8. Combine
combined = pd.concat([df1, df2_sample], ignore_index=True)
print("Combined shape (before dedup):", combined.shape)

# 9. Drop duplicates by text
combined = combined.drop_duplicates(subset=['sentence']).reset_index(drop=True)
print("After dedup:", combined.shape)

# 10. Verify that no label values are NaN
print("Missing labels:", combined['label'].isna().sum())
print("Label distribution:\n", combined['label'].value_counts())

# 11. Save final file
combined.to_csv("final_dataset_30k_fixed.csv", index=False)
print("✅ Saved as final_dataset_30k_fixed.csv")

cleaned_dataset_14k: (13966, 4)
Data.csv: (17000, 3)
df1 columns: Index(['id', 'sentence', 'label', 'sentiment'], dtype='object')
df2 columns: Index(['ID', 'Tweet', 'Sentiment Polarity'], dtype='object')

Unique Sentiment values before mapping: ['neutral' 'negative' 'positive']
Unique labels after mapping: [nan]
Data.csv sample shape: (16000, 3)
Sample label counts:
 Series([], Name: count, dtype: int64)
Combined shape (before dedup): (29966, 3)
After dedup: (29098, 3)
Missing labels: 15456
Label distribution:
 label
1.0    5132
2.0    4485
0.0    4025
Name: count, dtype: int64
✅ Saved as final_dataset_30k_fixed.csv

In [ ]:
import pandas as pd

df1 = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_14k.csv")
df2 = pd.read_csv("/Users/aashigarg/Downloads/Data.csv")

# Lowercase all sentiment strings
df2['Sentiment Polarity'] = df2['Sentiment Polarity'].str.lower()

# Map lowercase values to numeric labels
mapping = {"positive": 2.0, "neutral": 1.0, "negative": 0.0}
df2['label'] = df2['Sentiment Polarity'].map(mapping)

# Check mapping results
print("Unique mapped labels:", df2['label'].unique())

# Keep only necessary columns
df2 = df2[['ID', 'Tweet', 'label']].rename(columns={'ID': 'id', 'Tweet': 'sentence'})
df2_sample = df2.sample(n=16000, random_state=42)

# Combine with cleaned dataset
df1 = df1[['id', 'sentence', 'label']]
combined = pd.concat([df1, df2_sample], ignore_index=True)
combined = combined.drop_duplicates(subset=['sentence']).reset_index(drop=True)

# Final check
print("Missing labels:", combined['label'].isna().sum())
print("Label distribution:\n", combined['label'].value_counts())

combined.to_csv("final_dataset_30k_fixed.csv", index=False)
print("✅ Fixed dataset saved as final_dataset_30k_fixed.csv")

Unique mapped labels: [1. 0. 2.]
Missing labels: 0
Label distribution:
 label
1.0    10922
2.0     9571
0.0     8605
Name: count, dtype: int64
✅ Fixed dataset saved as final_dataset_30k_fixed.csv

In [ ]:
import pandas as pd
df = pd.read_csv("final_dataset_30k_fixed.csv")

for label, name in zip([0.0, 1.0, 2.0], ['Negative', 'Neutral', 'Positive']):
    print(f"\n{name} examples:")
    print(df[df['label'] == label].sample(3, random_state=int(label*10))['sentence'].to_list())

Negative examples:
['debat aakar ukhad lete fake news stori agenda chillat tameez nahi kisi', 'kaha gayi desh bhakti sardana sahab awaaz nahi utawog shame channel', 'certifi moron shame tmhi hamesha beizzati samna karna waqa certifi sazishi']

Neutral examples:
['guys follow my friend 17 she is very sweet person aapko acchi dost milegi koi follow back maat mangna f', 'global agenda sirf modi ke pas hai congress 72000 se vote kharidna chahti thi aur desh ke agende', 'grandmoth decid squash sardin patti good mix lunch h']

Positive examples:
['ji hind sudhir chaudhari sir meri puri famili aapko aapk show bahut pasand kart hain', 'dua love hero deserv love', 'young and energetic is the new mos congratulations and all the best awaaz modi2']

In [ ]:
df = df.dropna(subset=['sentence'])

In [ ]:
pip install emoji nltk unidecode

Requirement already satisfied: emoji in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (2.15.0)
Requirement already satisfied: nltk in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (3.9.2)
Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 2.9 MB/s eta 0:00:01
Requirement already satisfied: regex>=2021.8.3 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from nltk) (4.67.1)
Requirement already satisfied: click in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from nltk) (1.5.2)
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Users/aashigarg/Desktop/venv/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import re
import emoji
import nltk
from nltk.corpus import stopwords
from unidecode import unidecode
import pandas as pd

nltk.download('stopwords')

# Load your dataset
df = pd.read_csv("final_dataset_30k_fixed.csv")
df = df.dropna(subset=['sentence'])

# --- Hinglish normalization ---
hinglish_dict = {
    "acha": "achha", "accha": "achha", "achaa": "achha",
    "thik": "theek", "mast": "great", "bohot": "bahut",
    "bahot": "bahut", "nahi": "nahin", "nhi": "nahin",
    "pls": "please", "plz": "please", "frnd": "friend",
    "gud": "good", "luv": "love", "tera": "your", "meri": "my",
    "bht": "bahut", "bahut": "bahut", "kya": "what", "kyu": "why"
}

# --- Emoji to sentiment mapping ---
emoji_dict = {
    "😀": "happy", "😃": "happy", "😄": "happy", "😁": "happy",
    "😆": "laugh", "😂": "laugh", "🤣": "laugh", "😊": "happy",
    "😍": "love", "🥰": "love", "😘": "love", "😎": "cool",
    "😢": "sad", "😭": "cry", "😡": "angry", "😠": "angry",
    "❤️": "love", "💔": "broken_heart", "🔥": "amazing",
    "👍": "good", "👎": "bad", "🙏": "thankful", "👏": "applause"
}

stop_words = set(stopwords.words('english')) - {'not', 'no', 'nor'}

def emoji_to_word(text):
    for emj, meaning in emoji_dict.items():
        text = text.replace(emj, f" {meaning} ")
    return text

def clean_hinglish(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = emoji_to_word(text)
    text = re.sub(r"http\S+|www\S+|@\S+|#\S+", " ", text)
    text = re.sub(r"[^a-zA-Z!? ]", " ", text)
    for key, val in hinglish_dict.items():
        text = re.sub(r"\b" + re.escape(key) + r"\b", val, text)
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    tokens = [word for word in text.split() if word not in stop_words]
    text = " ".join(tokens)
    text = unidecode(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Apply cleaning
df['clean_text'] = df['sentence'].apply(clean_hinglish)

# Drop very short/gibberish lines
df = df[df['clean_text'].str.split().str.len() > 2]

# Save cleaned version
df.to_csv("final_dataset_30k_preprocessed.csv", index=False)

print("✅ Deep preprocessing + emoji mapping complete")
print("New shape:", df.shape)
print(df[['sentence', 'clean_text']].sample(5, random_state=42))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/aashigarg/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

✅ Deep preprocessing + emoji mapping complete
New shape: (28841, 4)
                                                sentence  \
5609   tangina im excited for my art after a year hah...
6145   pehle 55yr ki bat kar dalal rozgar de nahi pay...
7976   hi ajinkya never wanted you to face any such i...
14563  kumarji baaj nahi aog bhi mein modi fix kyu ap...
5259   librandus still don t digest modi as pm abhi t...

                                              clean_text
5609   tangina im excited art year hahaha matatapos k...
6145   pehle yr ki bat kar dalal rozgar de nahin paye...
7976   hi ajinkya never wanted face inconvenience ord...
14563  kumarji baaj nahin aog bhi mein modi fix apna ...
5259   librandus still digest modi pm abhi suruvat ha...

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")
encoded = tokenizer(" ".join(df['clean_text'].sample(100).tolist()))
print("Average tokens per sentence:", len(encoded['input_ids']) / 100)

/Users/aashigarg/Desktop/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Token indices sequence length is longer than the specified maximum sequence length for this model (2137 > 512). Running this sequence through the model will result in indexing errors

Average tokens per sentence: 21.37

In [ ]:
print(df['clean_text'].isna().sum())   # should be 0
print(df['label'].value_counts())      # sanity check balance
print(df['clean_text'].str.split().str.len().describe())  # length range

0
label
1.0    10764
2.0     9500
0.0     8577
Name: count, dtype: int64
count    28841.000000
mean        12.468881
std          5.342929
min          3.000000
25%          9.000000
50%         12.000000
75%         15.000000
max         85.000000
Name: clean_text, dtype: float64

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load your final preprocessed dataset
df = pd.read_csv("final_dataset_30k_preprocessed.csv")

# First split: train vs temp (val+test)
train_df, temp_df = train_test_split(
    df, test_size=0.3, stratify=df['label'], random_state=42
)

# Second split: validation vs test (equal split of 0.3)
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42
)

print(f"Train: {train_df.shape}, Val: {val_df.shape}, Test: {test_df.shape}")

# Save them
train_df.to_csv("train_21k.csv", index=False)
val_df.to_csv("val_4k.csv", index=False)
test_df.to_csv("test_4k.csv", index=False)

Train: (20188, 4), Val: (4326, 4), Test: (4327, 4)

In [ ]:
for name, split in [('Train', train_df), ('Validation', val_df), ('Test', test_df)]:
    print(f"\n{name} distribution:")
    print(split['label'].value_counts(normalize=True).round(3))

Train distribution:
label
1.0    0.373
2.0    0.329
0.0    0.297
Name: proportion, dtype: float64

Validation distribution:
label
1.0    0.373
2.0    0.329
0.0    0.297
Name: proportion, dtype: float64

Test distribution:
label
1.0    0.373
2.0    0.329
0.0    0.297
Name: proportion, dtype: float64

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from tqdm.notebook import tqdm  # tqdm for Jupyter-friendly progress bar
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

Device: cpu

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW

In [ ]:
import platform
print(platform.processor())

arm

In [ ]:
pip install torch torchvision torchaudio

Requirement already satisfied: torch in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (2.8.0)
Collecting torchvision
  Downloading torchvision-0.23.0-cp39-cp39-macosx_11_0_arm64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 2.9 MB/s eta 0:00:01
Collecting torchaudio
  Downloading torchaudio-2.8.0-cp39-cp39-macosx_11_0_arm64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 7.3 MB/s eta 0:00:01
Requirement already satisfied: networkx in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (3.2.1)
Requirement already satisfied: filelock in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (4.12.2)
Requirement already satisfied: jinja2 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (2025.10.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torch) (1.14.0)
Requirement already satisfied: numpy in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from torchvision) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/aashigarg/Desktop/venv/lib/python3.9/site-packages (from jinja2->torch) (3.0.2)
Installing collected packages: torchvision, torchaudio
Successfully installed torchaudio-2.8.0 torchvision-0.23.0
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Users/aashigarg/Desktop/venv/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import torch
print("PyTorch version:", torch.__version__)
print("MPS available:", torch.backends.mps.is_available())
print("MPS built:", torch.backends.mps.is_built())

PyTorch version: 2.8.0
MPS available: True
MPS built: True

In [ ]:
# Device setup for Apple Silicon (MPS)
import torch
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print("Device:", device)

Device: mps

In [ ]:
import torch
from transformers import BertForSequenceClassification

MODEL_NAME = "bert-base-multilingual-cased"

# Step 1: Always load checkpoint on CPU first
map_location = torch.device("cpu")
model = BertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=3)
model.load_state_dict(torch.load("best_mbert_model.pt", map_location=map_location))

# Step 2: Move to MPS after loading
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
model.to(device)

print("✅ Model reloaded successfully on", device)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ Model reloaded successfully on mps

In [ ]:
model.load_state_dict(torch.load("best_mbert_model.pt", map_location=device))

test_acc, test_p, test_r, test_f1 = evaluate(model, test_loader)
print("\n🎯 Final Test Results")
print(f"Accuracy:  {test_acc:.4f}")
print(f"Precision: {test_p:.4f}")
print(f"Recall:    {test_r:.4f}")
print(f"F1 Score:  {test_f1:.4f}")

🎯 Final Test Results
Accuracy:  0.6573
Precision: 0.6711
Recall:    0.6570
F1 Score:  0.6622

In [ ]:
best_f1 = 0    # or reuse your last known best if you tracked it
start_epoch = 3  # because epochs 1–3 are already done
epochs = 4

for epoch in range(start_epoch, epochs):
    model.train()
    train_loss = 0
    loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
    for batch in loop:
        optimizer.zero_grad()
        inputs = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**inputs)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        scheduler.step()
        train_loss += loss.item()
        loop.set_postfix(loss=loss.item())

    val_acc, val_p, val_r, val_f1 = evaluate(model, val_loader)
    print(f"\nEpoch {epoch+1}: Val Accuracy={val_acc:.4f}, F1={val_f1:.4f}")

    if val_f1 > best_f1:
        best_f1 = val_f1
        torch.save(model.state_dict(), "best_mbert_model.pt")
        print("✅ Model improved and saved!")
    else:
        print("⚠️ No improvement this epoch.")

Epoch 4/4:   0%|          | 0/2524 [00:00<?, ?it/s]

Epoch 4: Val Accuracy=0.6683, F1=0.6727
✅ Model improved and saved!

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load your dataset
df = pd.read_csv("/Users/aashigarg/Downloads/cleaned_dataset_updated11.csv").dropna(subset=["clean_text"])

# Map labels to numeric values
label_map = {"negative": 0, "neutral": 1, "positive": 2}
df["label"] = df["Sentiment"].map(label_map)

# Verify mapping
print(df["label"].value_counts())

label
1    2503
2    2104
0    2091
Name: count, dtype: int64

In [ ]:
import re

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    # Remove URLs, mentions, hashtags (keep the word after '#')
    text = re.sub(r"http\S+|www\S+|@\w+", "", text)
    text = re.sub(r"#", "", text)

    # Remove unwanted symbols but keep Hindi (Devanagari) + English words + emojis
    text = re.sub(r"[^a-zA-Z0-9\s\u0900-\u097F🙂😂😭😡😍😢😃😅🙄😉🙃😎🤔🤩❤️💕💔🔥🙌👏💯✨⭐🌟🙏]", " ", text)

    # Normalize elongated letters: e.g. "goooood" → "good"
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)

    # Replace multiple spaces with one
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply preprocessing
df["clean_text"] = df["clean_text"].apply(preprocess_text)

# Verify
df.head(10)

  Sentiment                                         clean_text  label
0  positive  aaj ka event bilkul faadu tha sabko zabardast ...      2
1  negative  uski acting mein koi jugaad nazar nahin aaya b...      0
2  positive  woh tapori style mein dance kar raha tha sab h...      2
3  positive  mera naya phone bomb nikla features ekdum lit ...      2
4  positive  party mein ek banda bilkul bindaas tha mood hi...      2
5   neutral  uske jokes full on bakchodi the thoda overthet...      1
6  negative  office mein sab log ekdum fukra lag rahe the k...      0
7   neutral  uski entry ne pure scene ko chikna bana diya s...      1
8  positive  aaj ke concert mein performance bilkul dhansu ...      2
9  positive  woh naya singer bilkul pataka nikla awaaz mein...      2

In [ ]:
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df["clean_text"],
    df["label"],
    test_size=0.2,
    stratify=df["label"],
    random_state=42
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.5,
    stratify=temp_labels,
    random_state=42
)

In [ ]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")

def tokenize_function(texts):
    return tokenizer(
        list(texts),
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)
test_encodings = tokenize_function(test_texts)

In [ ]:
import torch

class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels.iloc[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = SentimentDataset(train_encodings, train_labels)
val_dataset = SentimentDataset(val_encodings, val_labels)
test_dataset = SentimentDataset(test_encodings, test_labels)

In [ ]:
from transformers import BertForSequenceClassification, Trainer, TrainingArguments
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

model = BertForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=3
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=100,       # log progress every 100 steps
    save_total_limit=1,      # keep only last checkpoint
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro")
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/Users/aashigarg/Desktop/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/aashigarg/Desktop/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=1005, training_loss=0.5987524150022819, metrics={'train_runtime': 936.712, 'train_samples_per_second': 17.16, 'train_steps_per_second': 1.073, 'total_flos': 1057321269139968.0, 'train_loss': 0.5987524150022819, 'epoch': 3.0})

In [ ]:
trainer.evaluate(val_dataset)

/Users/aashigarg/Desktop/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'eval_loss': 0.6802661418914795,
 'eval_accuracy': 0.7343283582089553,
 'eval_macro_f1': 0.7373870618160884,
 'eval_runtime': 7.4841,
 'eval_samples_per_second': 89.523,
 'eval_steps_per_second': 2.806,
 'epoch': 3.0}

In [ ]:
trainer.evaluate(test_dataset)

/Users/aashigarg/Desktop/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

{'eval_loss': 0.6250131726264954,
 'eval_accuracy': 0.7492537313432835,
 'eval_macro_f1': 0.7528625642415615,
 'eval_runtime': 7.1459,
 'eval_samples_per_second': 93.76,
 'eval_steps_per_second': 2.939,
 'epoch': 3.0}